Full_Name = input("Enter your full name:")
Age = int(input("Enter your age:"))
Country = input("Enter your country:")
Grade = input("Enter your grade 'A', 'B', 'C': ")
Favroite_Subject = input("Enter your favroite subject: ")

print("======== STUDENT PROFILE =======")
print("Welcome," , Full_Name , "!")
print()
print("Name:" , Full_Name)
print("Age:" , Age)
print("Country:" ,Country)
print("Grade:" ,Grade)
print("Favorite Subject:" ,Favroite_Subject)
print()
print("================================")
